name: sample-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - xarray
  - zarr
  - matplotlib
  - cartopy
  - metpy
  - kerchunk
  - netcdf4
  - xarray-datatree
  - h5py
  - s3fs
  - pip
  - pip:
      - sphinx-pythia-theme
